stack=["Lecture A", "Lecture B", "Lecture C"]
stack.append("LectureA")
stack.append("LectureB")
stack.append("LectureC")
print("Initial stack:", stack)
stack.pop()
stack.pop()
print("Stack after undo two:", stack)
print("Top element is:", stack[-1])
stack = []
stack.append("StepA")
stack.append("StepB")
stack.append("StepC")
print("Initial stack:", stack)
stack.pop()
stack.pop()
stack.pop()
print("Stack after undo all:", stack)
stack = []
stack.extend(["X", "Y", "Z"])
print("After pushing X,Y,Z:", stack)
stack.pop()
stack.pop()
print("After popping two:", stack)
stack.append("w")